### ISSUE TITLE
Ability to move a grid element around the grid in the X, and Y directions, at the same time. 

### ISSUE THREAD

**Issue by jackson-sandland** [bokuweb/react-sortable-pane#109]
This is a feature question.

Is it possible to have the grid move very freely in the X, and Y directions as you drag. The way that react-grid-layout can move? Demo here: https://strml.github.io/react-grid-layout/examples/1-basic.html

beautiful work!

**Comment by bokuweb** [comment]
@jackson-sandland Thanks for your question :)
Sorry. That's impossible.

**Comment by jackson-sandland** [comment]
@bokuweb What makes it impossible?

**Comment by bokuweb** [comment]
It is possible, but I think it should be a separate package
