### ISSUE TITLE
Question regarding the pane order prop.

### ISSUE THREAD

**Issue by stozk** [bokuweb/react-sortable-pane#118]
Hi,

I'm using version 0.6.8.
I have modified the example with the controllers to dynamically add and delete panes.

Here's one thing I don't understand, unless I'm doing something wrong:

1. The "order" value, which is provided when the panes are being initialized in the [stories example](https://github.com/bokuweb/react-sortable-pane/blob/master/stories/vertical-pane-with-controller.js) doesn't seem to do anything and never seems to change when I log it in the onDragStop and onOrderChange.

...`this.state = {
      order: [0, 1, 2],
      list: [0, 1, 2].map(id => (`...
 
2. What's the use of the order prop in the pane, if you look at the demo log you'll also see that the array which is being logged in onDragStop has the proper order, but the order values never change, they actually represent the position of the pane at the time it was created.

Is the order prop there to represent the chronological order, not the current one and I have to get the current one programatically from the current array order?

BR
Daniel

**Comment by bokuweb** [comment]
@stozk Thanks for your report :) Sorry.  `order` is unused velue. It is never updated as after mounted. `order` is removed on v0.8.0. thanks :).
