### ISSUE TITLE
Is there any way to get the current order that the panes are in?

### ISSUE THREAD

**Issue by daversm** [bokuweb/react-sortable-pane#12]
I need a way to get the order of the panes. Is there an array I could look at too get that order.

**Comment by bokuweb** [comment]
Thunks @daversm 
Sorry, such API is not ready...
I'm going to implement callback with order as argument, when order chenged.

**Comment by daversm** [comment]
Thank you

**Comment by bokuweb** [comment]
I implement onOrderChange callback.
`onOrderChange` callback is called with order when pane order changed.

**Comment by hestacio** [comment]
If anyone was having same trouble as me in terms of the callback keeps returning the "old" order.  Use the second parameter of the call back instead

onOrderChange={(pane, newPanes) => alert(JSON.stringify(newPanes))}

**Comment by bokuweb** [comment]
I am planning to consider

**Comment by hestacio** [comment]
Why reopen? it works perfectly when calling the newPanes 
Thank you so much for this component

**Comment by bokuweb** [comment]
@hestacio oops. thanks!!
