### ISSUE TITLE
Sort, Drag, Resize does not work in Safari

### ISSUE THREAD

**Issue by imcodingideas** [bokuweb/react-sortable-pane#128]
### Overview of the problem

You're not able to drag, drop or resize in safari. Not even on the demo: http://bokuweb.github.io/react-sortable-pane/

Safari
Version 11.0.3 (13604.5.6)

**Comment by bokuweb** [comment]
@imcodingideas Thanks for your report :) Could you please try v0.7.1 ? thanks.

**Comment by bokuweb** [comment]
I close this issue for now, please re open it if you need
