### ISSUE TITLE
ETA on vertical panes?

### ISSUE THREAD

**Issue by haraldox** [bokuweb/react-sortable-pane#18]
@bokuweb Great component! Was looking all over the web for this, think I struck a gold mine with `react-sortable-pane`... How / Where did you get the inspiration? :)

Roadmap suggests vertical panes on the horizon, any ETA on that feature? How can I help?

I would also like to split panes when dragged on top of each other...

**Comment by bokuweb** [comment]
@haraldox Hi, thank you!!
`react-sortable-pane` is inspired with `react-motion` example.

I`m going to support children remove and append.
Next, I'll imeplement vertical pane.

If the children remove and append feature implementation is complete, Please help me.
But if you think `vertical panes on the horizon` feature on this component, It may be better to create another component.

**Comment by bokuweb** [comment]
@haraldox Hi! I Implement vertical mode on v0.2.0.
Please re-open if there is a problem.
thanks.
