### ISSUE TITLE
[Feature request] Fit to the parent container

### ISSUE THREAD

**Issue by zalmoxisus** [bokuweb/react-sortable-pane#20]
First of all, pretty neat implementation! Probably this feature request should be implemented as another component, I think usually we don't want horizontal scrolling or the elements to go out of the visible area. So, it would be great if by dragging an element edge, it would resize the next one as well to keep them fitted into the parent container. I guess it would be useful [for your example](http://cdn-ak.f.st-hatena.com/images/fotolife/b/bokuweb/20160131/20160131165555.gif) as well.

**Comment by bokuweb** [comment]
@zalmoxisus  Hi! Thank you for the request!!
Are you of the request, such as the following work?

http://react-split-pane.surge.sh/

**Comment by zalmoxisus** [comment]
Thanks for the link! Yes, something like that, except the fact that those panes aren't draggable.

To implement this here, we would need to use flex-box, which will probably break the animation effects. So, I guess it wouldn't be possible, right?

I want to use it for adding multiple monitors in [Remote Redux Devtools](https://github.com/zalmoxisus/remote-redux-devtools) exactly as [in your example](http://cdn-ak.f.st-hatena.com/images/fotolife/b/bokuweb/20160131/20160131165555.gif).

**Comment by bokuweb** [comment]
@zalmoxisus Thank you for answering!!

> To implement this here, we would need to use flex-box, which will probably break the animation effects. So, I guess it wouldn't be possible, right?

Ummm.If use flex-box, I think difficult to implement animation effects.
If you want to implement  animation effects, It may be better to resizable component (like http://bokuweb.github.io/react-resizable-box/example/) and calculate the width manually.

> I want to use it for adding multiple monitors in Remote Redux Devtools exactly as in your example.

Remote Redux Devtools!! It is a cool extension!!!

Either way, it is looks good better to implemented as another component.

**Comment by zalmoxisus** [comment]
Thanks a lot for the details, @bokuweb! Will look into those examples.

**Comment by bokuweb** [comment]
Or, when pane resized, recieve pane width as callback argument, then all pane width calculate manually based on the parent's element size on parent component.
