### ISSUE TITLE
added panes in wrong position

### ISSUE THREAD

**Issue by helicese** [bokuweb/react-sortable-pane#226]
### Overview of the problem

I'm using react-sortable-pane **version** [1.0.2] 
My **browser** is:  Chrome 69.0.3497.81
I am sure this issue is **not a duplicate**
https://codesandbox.io/embed/r5x8x63v1n

### Description
After init, I try to add panes to the sortablePane, but I find that the added panes are in the wrong place after the second insert.

### Steps to Reproduce

1. In the demo before, just click the add button twice，you will find the problem

### Expected behavior
added panes in the right position

### Actual behavior
added panes in the wrong position, with a large blank space

### My options
actually I find the reason after debugging. In the function below
```
   getPaneSizeList(): Array<number> {
    const width = this.panes.map((pane: PaneProperty) =>
      Number((pane.ref && (pane.ref as HTMLElement).offsetWidth) || 0),
    );
    const height = this.panes.map((pane: PaneProperty) =>
      Number((pane.ref && (pane.ref as HTMLElement).offsetHeight) || 0),
    );
    return this.isHorizontal() ? width : height;
  }
```
Seems the function is fine. but let's see the Dom
![image](https://user-images.githubusercontent.com/5021538/45550899-dc76a600-b85e-11e8-997a-61a079a4518c.png)
There is a div with className `__resizable_base__`, which will be involved in the calculation of next pane's position. This lead to the wrong position of the new added panes.
I know the reason but cannot find a way to fix it. Help is needed.

**Comment by fijiwebdesign** [comment]
The issue still exists in version `1.0.4`

Update: The hack fix is to add the className `__resizable_base__` to each pane. 

```
<Pane 
        className="__resizable_base__"
      >
```

**Comment by fijiwebdesign** [comment]
After a lot of headache, the current hacky solution to this is to just remove any instances of `__resizable_base__` before any dom updates. 

```
componentWillUpdate() {
    const { panesWrapper } = this.panesRef
    const rzBase = panesWrapper.querySelector('.__resizable_base__')
    if (rzBase) {
      panesWrapper.removeChild(rzBase)
    }
  }
```

In render
```
<SortablePane 
          ref={ref => this.panesRef = ref}
          direction="vertical"
          style={{
            height: this.getContentHeight()
          }}
        >
```

You may also have to calculate the exact height of the panes. 

```
getContentHeight() {
    return (this.props.list.items.length * this.props.itemHeight) + 'px'
  }
```

**Comment by helicese** [comment]
Thank you for what you have done, but the given solution still bothers me. Actually, I switch to other sortable lib with more stars, which is easy to use by the way

**Comment by fijiwebdesign** [comment]
@helicese  Which lib did you use? I'm still looking for one.

**Comment by helicese** [comment]
https://github.com/atlassian/react-beautiful-dnd
https://github.com/RubaXa/Sortable
...
you can just seach on github

**Comment by oskvortsov** [comment]
I find the ugly fix for this bug
You should update key pane when list items change (add/remove)
https://codesandbox.io/s/hack-react-sortable-pane-4jvhn?file=/src/List.tsx
