### ISSUE TITLE
getting error when running example

### ISSUE THREAD

**Issue by haraldox** [bokuweb/react-sortable-pane#23]
`warning.js:45 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of`PaneStack`.warning`

`Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of`PaneStack`.`

**Comment by bokuweb** [comment]
@haraldox thanks please tell me a your browser and npm version.

**Comment by haraldox** [comment]
@bokuweb still testing, will do

**Comment by haraldox** [comment]
@bokuweb alright, my mistake! took an old import statement from previous releases:

> `import SortablePane, { Pane } from 'react-sortable-pane'`

instead of the correct version

> `import { SortablePane, Pane } from 'react-sortable-pane'`

all fine now! :+1:

**Comment by bokuweb** [comment]
@haraldox  oh... sorry.... i'll fix doc and example.thanks!!

**Comment by mikeplis** [comment]
@bokuweb this might be a noob question, but how do I run the example? I'd like to see some add/remove functionality on display and it looks like the example does this, but I can't figure out how to run it.

**Comment by bokuweb** [comment]
@mplis Please download https://github.com/bokuweb/react-sortable-pane/archive/v0.2.4.zip

```
$ cd react-sortable-pane-0.2.4
$ npm i
$ npm run watch
```

```
$ open example/index.html
```
