### ISSUE TITLE
Mix horizontal and vertical panes

### ISSUE THREAD

**Issue by haraldox** [bokuweb/react-sortable-pane#24]
@bokuweb: great work on version 0.2.0! :)

now that you got vertical panes implemented (by popular demand ;) how much effort would it be in your opinion, to mix horizontal and vertical panes, i.e. freely drag horizontal to vertical panes and vice versa?

see [yellowiscool/LeCadreur](http://yellowiscool.github.io/LeCadreur/example/index.html) as an example (click on flip - top right corner and then drag by color handles)

also kind of like a combined version of [STRML/react-grid-layout](https://github.com/STRML/react-grid-layout) and its horizontal counterpart [cmelion/react-grid-layout](https://github.com/cmelion/react-grid-layout)

or even [gridster.js](http://gridster.net/)

Thanks for your feedback! I checked out your github repos as well as blog and you have very interesting projects ... I can feel this component becoming big!

**Comment by bokuweb** [comment]
@haraldox Hi! Thanks for the link!

Your image is `react-split-pane`(http://react-split-pane.surge.sh/) where sortable/draggable feature is added?
And It's same demand this request? https://github.com/bokuweb/react-sortable-pane/issues/20

And if so, It should be implemented as another component(like, `react-sortable-split`)
I'll going to implement  `react-sortable-split`, but It is earlier to complete a `react-sortable-pane`.
Does it is useless for `STRML/react-grid-layout` is not that  freely drag(possible grid drag)?

> Thanks for your feedback! I checked out your github repos as well as blog and you have very interesting projects ... I can feel this component becoming big!

thanks!!

**Comment by haraldox** [comment]
+1

indeed, for me react-grid-layout is not suitable because you can drag elements either vertically or horizontally but not both. also, no splitting there like [LeCadreur](http://yellowiscool.github.io/LeCadreur/example/index.html)

Actually, I think your library could be a long-awaited and worthy competitor to @deepstreamIO's commercial solution [GoldenLayout](https://golden-layout.com) which is open source but GPL-licensed ([deepstreamIO/golden-layout](https://github.com/deepstreamIO/golden-layout)) **but doesn't use absolute positioning.** Especially augmenting that library with react would be interesting...

future library `react-sortable-split` would also be an alternative to @tomkp's excellently simple and elegant [react-split-pane](http://react-split-pane.surge.sh/) maybe inciting friendly competition? ;)

hope my positive feedback is constructive! :)

**Comment by bokuweb** [comment]
@haraldox Thanks for the link and thanks your feedback.
I will use GoldenLayout  as reference.

If I started to implement the react-sortable-split, we will contact you

**Comment by haraldox** [comment]
wow, that was fast! :)

**Comment by haraldox** [comment]
@bokuweb Just to update you: GoldenLayout will be updated to support React, but probably still won't support absolute positioning ... can you give me a few pointers on how to implement react-sortable-split? maybe we can collaborate! :)

**Comment by bokuweb** [comment]
@haraldox oh.thanks.
Are you in a hurry?
I'm going to create `react-sortable-split` prototype this or next holiday.

**Comment by haraldox** [comment]
@bokuweb Yes, I am but no worries... ;-)

just out of curiosity, what do you mean by "holiday" in japan? thanks

**Comment by bokuweb** [comment]
> what do you mean by "holiday" in japan?

It means, this weekend or next weekend.
I'll try if possible 

https://github.com/bokuweb/react-sortable-split

**Comment by haraldox** [comment]
@bokuweb Wow, that's fast! Thanks for the update :+1: keep up the great work! :)
