### ISSUE TITLE
Easiest way to achieve full height / width panes?

### ISSUE THREAD

**Issue by haraldox** [bokuweb/react-sortable-pane#25]
@bokuweb In The Code of dependancy ‘react-resizable-box’ the string ’px’ is always appended to this.state.height and this.state.width in the component’s render() method

I tried hacking it but fruitless for now ... Any tips on how to achieve this without changes in your packages?

**Comment by bokuweb** [comment]
@haraldox Do you mean you want to set width & height 100%?

**Comment by haraldox** [comment]
yes exactly!

**Comment by bokuweb** [comment]
@haraldox thanks. I try to support % size.
May I have a moment of your time?

**Comment by haraldox** [comment]
sure, shoot!
