### ISSUE TITLE
width / height do not change via props

### ISSUE THREAD

**Issue by haraldox** [bokuweb/react-sortable-pane#27]
hi there again @bokuweb, i'm not done making trouble! :)

if i've read your code correctly, the Pane component is not stateless, i.e. always same behavior with same props because when I change props `width` or `height` on `<Pane>`, box dimensions do not change but stay at the initial sizes...

Is that behavior on purpose? I would need to support resizing the box programmatically as well (not only via the resizers...)

As always, Any feedback is appreciated! ;) Thanks

**Comment by bokuweb** [comment]
Hi @haraldox 

Oh..sorry.`react-sortable-pane` use `react-resizable-box`.
`react-resizable-box` is not support update width and height by props.
It is a  problem. I'm going to solve this issue.

**Comment by haraldox** [comment]
oh wow great! :)) any ETA? i know your great work on `react-sortable-pane` and `react-resizable-box` takes a great deal of your time and I thank you so much for it!!

any way I could help?

**Comment by bokuweb** [comment]
I want to start this week.

**Comment by haraldox** [comment]
ok great, then I'll wait for your implementation. Also, I'll file another feature request that would come in handy :P

**Comment by bokuweb** [comment]
@haraldox Fix this issue, on v0.2.3

**Comment by haraldox** [comment]
THANK YOU SO MUCH :)
please keep up the great work ;)

PS: According to the repository stars on gh, `react-sortable-pane` is starting to get traction :+1:

**Comment by haraldox** [comment]
@bokuweb please review my pull request and tell me if i'm on the right track ... been chasing this bug for a week now
