### ISSUE TITLE
[feature request] show / hide panes

### ISSUE THREAD

**Issue by haraldox** [bokuweb/react-sortable-pane#28]
since panes are positioned `absolute`, we can't show or hide panes with the CSS `display: none` property, the other panes would remain in place....

@bokuweb I'll try to implement that functionality myself though, don't want you to work for my requirements - i'm sure you have a day job ;)

**Comment by bokuweb** [comment]
@haraldox If you want to hide pane, try bellow example code.

``` js
      <SortablePane
          direction="vertical"
          margin={10}
          onResize={(id, dir, size, rect) => null}
          onOrderChange={(panes) => null}
      >
        { this.state.isHide ? null : <Pane>A</Pane>}
        <Pane>B</Pane>
      </SortablePane>
```

**Comment by haraldox** [comment]
I know, but I can't have the contents removed from DOM.
As it's an `<iframe>` it will get reloaded on show.

There are 3 approaches I'm currently trying:
1. set pane width to `0`, does not work because of absolute positioning... will have to wait for your dynamic size fix
2. move pane to hide to end i.e. shuffle the order around and then use `display:none` on the last panes... however i'm not sure what will happen when the last visible pane is interactively dragged...
3. remove the absolute positioning and just move pane offscreen, however that would probably mess up the order too...

i'm in a bit of a conundrum! :/

**Comment by haraldox** [comment]
could this be achieved using the new prop `order`?
