### ISSUE TITLE
question: how to create two panes always spanning 100% width together

### ISSUE THREAD

**Issue by barbalex** [bokuweb/react-sortable-pane#31]
Sorry to span Issues. But I believe this could be helpful for other people too.

I want to create a view with two columns.

The user shall be able to horizontally expand one column. When he does this, the other column should correspondingly reduce width so that both columns together always span 100% of width.

I believe this could be achieved with an `onResize` handler on `SortablePane`: on resize a function would reduce the width of the other pane.

I am a bit of a react noob. Could you tell me if this idea is correct and maybe how to set the width of a pane in a function?

**Comment by zalmoxisus** [comment]
Related to https://github.com/bokuweb/react-sortable-pane/issues/20.

**Comment by bokuweb** [comment]
@zalmoxisus thanks!!

@barbalex thanks your request.
I made a simple example.

``` js
import React, { Component } from 'react';
import { SortablePane, Pane } from '../../src';

const style = {
  fontSize: '40px',
  textAlign: 'center',
  height: '100%',
  border: 'solid 1px #ccc',
  borderRadius: '5px',
  backgroundColor: '#fff',
};

export default class Example extends Component {
  constructor(props) {
    super(props);
    this.state = { width: [400, 400] };
  }

  onResize({id, size}) {
    let width = [];
    width[id] = size.width;
    width[(id+1)%2] = 800 - size.width;
    this.setState({ width });
  }

  render() {
    return (
      <div style={{ width: '800px', height: '600px' }}>
        <SortablePane
          direction="horizontal"
          margin={10}
          onResize={::this.onResize}
        >
        <Pane
          id={0}
          ref="pane0"
          width={this.state.width[0]}
          height={600}
          style={style}
        />
        <Pane
          id={1}
          ref="pane1"
          width={this.state.width[1]}
          height={600}
          style={style}
        />
        </SortablePane>
      </div>
    );
  }
}
```

![screenshot](https://cloud.githubusercontent.com/assets/10220449/14206807/ac58a3e0-f850-11e5-9a08-c41893d6f176.gif)

But, position not updated properly.
This component is not suitable...
I think it is looks good better to implemented as another component.

I'm going to create such components.
But this tasks that take a long time to complete.
https://github.com/bokuweb/react-sortable-split

**Comment by barbalex** [comment]
thanks a lot
will watch your projects
in the meantime I am reverting to a simple solution without split

**Comment by bokuweb** [comment]
@barbalex sorry... I'll do my best.

**Comment by barbalex** [comment]
thanks for great tools and stellar help :-)
