### ISSUE TITLE
Prevent Sorting Condition?

### ISSUE THREAD

**Issue by ganapativs** [bokuweb/react-sortable-pane#34]
Can we prevent sorting if certain condition is met?

**Comment by bokuweb** [comment]
Please use `e.stopPropagation()`, when you want to prevent sorting.

```
<SortablePane>
  <Pane>
    <div onMouseDown={(e) => e.stopPropagation()}>your contents</div>
  </Pane>
</SortablePane>
```

**Comment by IanVS** [comment]
It would be very nice if there was a prop on `<SortablePane />` of `sortingEnabled`.  My use case for a tool like this is a dashboard which normally is not sortable unless the user is in an "edit" mode.  Setting `stopPropagation` on each individual `<Pane />` is less than ideal for that.

**Comment by bokuweb** [comment]
@IanVS thanks!!! it's look good to me.
I'm going to implement `sortingEnable` props!!

**Comment by IanVS** [comment]
I can take a shot at this if you don't have time.  Any specifics of how you'd like it to be implemented?

**Comment by bokuweb** [comment]
@IanVS Oh.., Your help is essential.Tank you very much!!!
