### ISSUE TITLE
Resizing first pane when disableEffect=true

### ISSUE THREAD

**Issue by IanVS** [bokuweb/react-sortable-pane#39]
I've encountered a strange behavior that only exists when `disableEffect={true}`.  I have vertical panes, and when changing the `y` size of the first pane, it jumps to the same position as the second pane when releasing the mouse.  It then jumps right back to its right spot if the mouse is clicked again.  This does not happen when moving the second pane, even after it is rearranged.  Take a look at the gif below.  

If you have trouble reproducing, I'll try to create a minimal case.  I had a look through the source, but couldn't figure out why this is happening.  I believe it has to do with the `translate3d` not updating correctly, but that's as far as I got.

![sortable-pane-jumping](https://cloud.githubusercontent.com/assets/4616705/15157964/d901ee9a-16bb-11e6-9d3d-f9071e0bdb61.gif)

**Comment by bokuweb** [comment]
@IanVS Thank you for your report!!
Ummm,It is strange.....

I'm going to try to reproduce it and investigate. thanks!

**Comment by bokuweb** [comment]
closed by #40
