### ISSUE TITLE
Demo failing

### ISSUE THREAD

**Issue by marin101** [bokuweb/react-sortable-pane#53]
I was playing around with your demo and it crashed.

I hope my screenshot will help you:
![screenshot from 2017-02-14 19 53 50](https://cloud.githubusercontent.com/assets/22985405/22944058/d0f0d5ca-f2ef-11e6-89c8-6708d6f249fa.png)

**Comment by IanVS** [comment]
It seems to work okay for me.  What browser are you using?  And what did you do which caused it to crash?

**Comment by marin101** [comment]
Here is what I did: move 2 to the top, press "remove", move 3 to the top. 3 gets glued over 1, and now if you try touching 1 `TypeError` is thrown.

**Comment by marin101** [comment]
I'm not sure which box gets deleted when I press "remove". It seems random to me. In the example above 2 (the top one) got removed

**Comment by bokuweb** [comment]
@marin101 Thanks for your report.It's not reproduced in my env... I'll investigate it.

>  It seems random to me.

it is ramdom now.

**Comment by marin101** [comment]
Also if it helps, I was trying it out on Google Chrome (Version 56.0.2924.87 (64-bit)), Ubuntu 14.04

**Comment by bokuweb** [comment]
@marin101 thanks!
