### ISSUE TITLE
onDragStop event is bubbled up to window, instead of being tied to parent element

### ISSUE THREAD

**Issue by browne0** [bokuweb/react-sortable-pane#92]
### Overview of the problem

I'm using react-sortable-pane **version** [0.6.5]
My **browser** is: Google Chrome
I am sure this issue is **not a duplicate**?

### Description

onDragStop event is bubbled up to the window for whatever reason instead of being tied to a parent element. This causes it to be called whenever someone clicks anywhere on the page. I believe it's the same for multiple other methods.

A thing to note is that I'm also using the drag handler. Not sure if there's a bug with that rather than the event itself.

### Steps to Reproduce

1. Add onDragStop to your SortablePane component
2. console.log(panes)
3. Check console

### Expected behavior

It should log the changed panes after you stop dragging.

### Actual behavior

It logs the changed panes everytime you click on the page, regardless if you click on the handle or element.

**Comment by browne0** [comment]
I have switched to a new project that better suits my development needs. Thanks for the awesome project though! :+1:

**Comment by mergebandit** [comment]
This should really be re-opened as this issue still persists. FWIW I'm not using drag handler.
